language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-o
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.0-preview
  - build-tools-25.0.3
  - android-25
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - '.+'
script:
  - ./gradlew build
  - ${ANDROID_HOME}tools/bin/sdkmanager --channel=3 \
      "tools" "platform-tools" "build-tools;26.0.0-rc2" "platforms;android-O" \
      "extras;google;google_play_services"
